name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and compile check
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      - name: Show current version of Xcode
        run: xcodebuild -version

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Run build script
        run: ./run_build.sh
