name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build and test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show current version of Xcode
        run: xcodebuild -version

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Run tests
        run: ./run_tests.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            *.xcresult
