name: iOS Tests

on:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: Create dummy config files
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>API_URL</key>
            <string>https://api.example.com</string>
          </dict>
          </plist>' > Config.plist

          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>BUNDLE_ID</key>
            <string>com.thrive-fl.ThriveCommunityChurch</string>
            <key>PROJECT_ID</key>
            <string>dummy-project</string>
            <key>GOOGLE_APP_ID</key>
            <string>1:123456789:ios:dummy</string>
          </dict>
          </plist>' > GoogleService-Info.plist

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -workspace "Thrive Church Official App.xcworkspace" \
            -scheme "Thrive Church Official App" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGNING_ALLOWED=NO \
            -only-testing:"Thrive Church Official AppTests"

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -workspace "Thrive Church Official App.xcworkspace" \
            -scheme "Thrive Church Official App" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGNING_ALLOWED=NO \
            -only-testing:"Thrive Church Official AppUITests"
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            *.xcresult
